/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablePlannerRouteImport } from './routes/table-planner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrderRouteImport } from './routes/order'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CakesRouteImport } from './routes/cakes'
import { Route as CakeBuilderRouteImport } from './routes/cake-builder'
import { Route as ArRouteImport } from './routes/ar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as CakesIndexRouteImport } from './routes/cakes.index'
import { Route as MenuCategoryRouteImport } from './routes/menu.$category'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as CakesSlugRouteImport } from './routes/cakes.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as MenuCategorySlugRouteImport } from './routes/menu.$category.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TablePlannerRoute = TablePlannerRouteImport.update({
  id: '/table-planner',
  path: '/table-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CakesRoute = CakesRouteImport.update({
  id: '/cakes',
  path: '/cakes',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeBuilderRoute = CakeBuilderRouteImport.update({
  id: '/cake-builder',
  path: '/cake-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationsRoute,
} as any)
const CakesIndexRoute = CakesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CakesRoute,
} as any)
const MenuCategoryRoute = MenuCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MenuRoute,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const CakesSlugRoute = CakesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CakesRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuCategorySlugRoute = MenuCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MenuCategoryRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/cake-builder': typeof CakeBuilderRoute
  '/cakes': typeof CakesRouteWithChildren
  '/catering': typeof CateringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/locations': typeof LocationsRouteWithChildren
  '/mcp': typeof McpRoute
  '/menu': typeof MenuRouteWithChildren
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/table-planner': typeof TablePlannerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cakes/$slug': typeof CakesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/menu/$category': typeof MenuCategoryRouteWithChildren
  '/cakes/': typeof CakesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/cake-builder': typeof CakeBuilderRoute
  '/catering': typeof CateringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/table-planner': typeof TablePlannerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cakes/$slug': typeof CakesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/menu/$category': typeof MenuCategoryRouteWithChildren
  '/cakes': typeof CakesIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/menu': typeof MenuIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ar': typeof ArRoute
  '/cake-builder': typeof CakeBuilderRoute
  '/cakes': typeof CakesRouteWithChildren
  '/catering': typeof CateringRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/locations': typeof LocationsRouteWithChildren
  '/mcp': typeof McpRoute
  '/menu': typeof MenuRouteWithChildren
  '/order': typeof OrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/table-planner': typeof TablePlannerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cakes/$slug': typeof CakesSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/menu/$category': typeof MenuCategoryRouteWithChildren
  '/cakes/': typeof CakesIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ar'
    | '/cake-builder'
    | '/cakes'
    | '/catering'
    | '/llms.txt'
    | '/locations'
    | '/mcp'
    | '/menu'
    | '/order'
    | '/sitemap.xml'
    | '/table-planner'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cakes/$slug'
    | '/locations/$slug'
    | '/menu/$category'
    | '/cakes/'
    | '/locations/'
    | '/menu/'
    | '/.mcp/invoke-tool/$tool'
    | '/menu/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ar'
    | '/cake-builder'
    | '/catering'
    | '/llms.txt'
    | '/mcp'
    | '/order'
    | '/sitemap.xml'
    | '/table-planner'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cakes/$slug'
    | '/locations/$slug'
    | '/menu/$category'
    | '/cakes'
    | '/locations'
    | '/menu'
    | '/.mcp/invoke-tool/$tool'
    | '/menu/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ar'
    | '/cake-builder'
    | '/cakes'
    | '/catering'
    | '/llms.txt'
    | '/locations'
    | '/mcp'
    | '/menu'
    | '/order'
    | '/sitemap.xml'
    | '/table-planner'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cakes/$slug'
    | '/locations/$slug'
    | '/menu/$category'
    | '/cakes/'
    | '/locations/'
    | '/menu/'
    | '/.mcp/invoke-tool/$tool'
    | '/menu/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArRoute: typeof ArRoute
  CakeBuilderRoute: typeof CakeBuilderRoute
  CakesRoute: typeof CakesRouteWithChildren
  CateringRoute: typeof CateringRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  McpRoute: typeof McpRoute
  MenuRoute: typeof MenuRouteWithChildren
  OrderRoute: typeof OrderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TablePlannerRoute: typeof TablePlannerRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table-planner': {
      id: '/table-planner'
      path: '/table-planner'
      fullPath: '/table-planner'
      preLoaderRoute: typeof TablePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cakes': {
      id: '/cakes'
      path: '/cakes'
      fullPath: '/cakes'
      preLoaderRoute: typeof CakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cake-builder': {
      id: '/cake-builder'
      path: '/cake-builder'
      fullPath: '/cake-builder'
      preLoaderRoute: typeof CakeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/locations/': {
      id: '/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/cakes/': {
      id: '/cakes/'
      path: '/'
      fullPath: '/cakes/'
      preLoaderRoute: typeof CakesIndexRouteImport
      parentRoute: typeof CakesRoute
    }
    '/menu/$category': {
      id: '/menu/$category'
      path: '/$category'
      fullPath: '/menu/$category'
      preLoaderRoute: typeof MenuCategoryRouteImport
      parentRoute: typeof MenuRoute
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/cakes/$slug': {
      id: '/cakes/$slug'
      path: '/$slug'
      fullPath: '/cakes/$slug'
      preLoaderRoute: typeof CakesSlugRouteImport
      parentRoute: typeof CakesRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$category/$slug': {
      id: '/menu/$category/$slug'
      path: '/$slug'
      fullPath: '/menu/$category/$slug'
      preLoaderRoute: typeof MenuCategorySlugRouteImport
      parentRoute: typeof MenuCategoryRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CakesRouteChildren {
  CakesSlugRoute: typeof CakesSlugRoute
  CakesIndexRoute: typeof CakesIndexRoute
}

const CakesRouteChildren: CakesRouteChildren = {
  CakesSlugRoute: CakesSlugRoute,
  CakesIndexRoute: CakesIndexRoute,
}

const CakesRouteWithChildren = CakesRoute._addFileChildren(CakesRouteChildren)

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface MenuCategoryRouteChildren {
  MenuCategorySlugRoute: typeof MenuCategorySlugRoute
}

const MenuCategoryRouteChildren: MenuCategoryRouteChildren = {
  MenuCategorySlugRoute: MenuCategorySlugRoute,
}

const MenuCategoryRouteWithChildren = MenuCategoryRoute._addFileChildren(
  MenuCategoryRouteChildren,
)

interface MenuRouteChildren {
  MenuCategoryRoute: typeof MenuCategoryRouteWithChildren
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCategoryRoute: MenuCategoryRouteWithChildren,
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArRoute: ArRoute,
  CakeBuilderRoute: CakeBuilderRoute,
  CakesRoute: CakesRouteWithChildren,
  CateringRoute: CateringRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LocationsRoute: LocationsRouteWithChildren,
  McpRoute: McpRoute,
  MenuRoute: MenuRouteWithChildren,
  OrderRoute: OrderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TablePlannerRoute: TablePlannerRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
